name: Trigger rebuilds

on: 
  schedule:
    - cron:  '0 0 * * *'

jobs:
  rebuild:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
      - name: Touch a file
        run: date +%s > .rebuild
      - name: Commit touched file
        run: git add .rebuild && git commit -m 'Trigger rebuild'
      - name: Push change
        run: git push origin HEAD
